// Reporting-only expansion of the retained strategy inputs. These are discovery
// estimates, not survey results. Legacy coordinates are retained only where the
// outcome still describes the same reporting job; other coordinates are new
// management estimates recorded on 2026-09-16.
export const reportingOutcomes = [
  {
    id: "R1",
    theme: "Unify",
    text: "Assemble a branded, client-ready report in one tool.",
    imp: 9.5,
    sat: 2.0,
    basis: "derived",
    origin: "Legacy ODI #5.1; original 9.5 / 2.0 ratings retained.",
    sources: ["addepar"],
    ux: "Keep client, template, content and generation in one reporting workspace.",
    tab: "build",
  },
  {
    id: "R2",
    theme: "Unify",
    text: "Reduce the tools needed to assemble and finish a report.",
    imp: 9.4,
    sat: 2.0,
    basis: "derived",
    origin:
      "Legacy ODI #5.3, narrowed to report assembly; original 9.4 / 2.0 ratings retained.",
    sources: ["addepar"],
    ux: "Carry report configuration forward without rebuilding the package in another tool.",
    tab: "build",
  },
  {
    id: "R3",
    theme: "Unify",
    text: "Include the client's full household and account context.",
    imp: 9.4,
    sat: 2.5,
    basis: "derived",
    origin:
      "BD-HA #1, applied to reporting scope; original 9.4 / 2.5 ratings retained.",
    sources: ["advisor360", "finraSnapshot"],
    ux: "Make included and missing accounts visible before report assembly.",
    tab: "build",
  },
  {
    id: "R4",
    theme: "Unblock",
    text: "Find missing or stale source data before generating a draft.",
    imp: 9.2,
    sat: 2.7,
    basis: "inferred",
    origin:
      "New management estimate from the Locate/Prepare job-map hypothesis; no measured reporting baseline.",
    sources: ["schwabStudy"],
    ux: "Show data freshness, missing inputs and the owner of each correction before generation.",
    tab: "generate",
  },
  {
    id: "R5",
    theme: "Explain",
    text: "Explain results in the right brokerage or advisory context.",
    imp: 9.1,
    sat: 2.7,
    basis: "derived",
    origin:
      "BD-HA #2; original 9.1 / 2.7 ratings retained as a reporting estimate.",
    sources: ["finraAI", "finra2210"],
    ux: "Bind narrative and disclosures to the selected account context.",
    tab: "customize",
  },
  {
    id: "R6",
    theme: "Explain",
    text: "Trace each narrative claim to its supporting data.",
    imp: 9.3,
    sat: 2.4,
    basis: "inferred",
    origin:
      "New management estimate from the proposed reporting control layer; vendor evidence does not establish a complete implementation.",
    sources: ["orion", "tamarac"],
    ux: "Let the reviewer inspect the data behind each generated statement and reject unsupported claims.",
    tab: "customize",
  },
  {
    id: "R7",
    theme: "Explain",
    text: "Use approved language and disclosures in the report.",
    imp: 8.6,
    sat: 3.2,
    basis: "derived",
    origin: "BD-HA #5; original 8.6 / 3.2 ratings retained.",
    sources: ["finra2210", "marketing"],
    ux: "Apply approved language rules while authors customize the report.",
    tab: "customize",
  },
  {
    id: "R8",
    theme: "Route",
    text: "Send a reporting issue to its owner with the evidence attached.",
    imp: 8.8,
    sat: 3.1,
    basis: "derived",
    origin:
      "BD-HA #4, narrowed to reporting handoffs; original 8.8 / 3.1 ratings retained.",
    sources: ["schwabStudy"],
    ux: "Attach the blocker, due date, correction history and next action to the handoff.",
    tab: "generate",
  },
  {
    id: "R9",
    theme: "Prove",
    text: "Know who approved the exact report version ready for release.",
    imp: 9.4,
    sat: 2.8,
    basis: "inferred",
    origin:
      "New management estimate from the named-approval proposal; no observed approval-cycle baseline.",
    sources: ["finra2210"],
    ux: "Show a named review decision against an immutable report version before release.",
    tab: "generate",
  },
  {
    id: "R10",
    theme: "Prove",
    text: "Retrieve the sent report, approval and source history together.",
    imp: 8.5,
    sat: 2.8,
    basis: "derived",
    origin:
      "Legacy ODI #15, made specific to reporting evidence; original 8.5 / 2.8 ratings retained.",
    sources: ["finra2231"],
    ux: "Keep the delivered version linked to its source snapshot, review and delivery record.",
    tab: "generate",
  },
  {
    id: "R11",
    theme: "Route",
    text: "Complete a reporting cycle with clear status and recovery steps.",
    imp: 8.7,
    sat: 3.4,
    basis: "inferred",
    origin:
      "New management estimate from the generation and delivery journey; deadlines and failure rates are unmeasured.",
    sources: ["addepar", "finra2231"],
    ux: "Expose stage status, failure reasons and retry ownership for each package.",
    tab: "generate",
  },
  {
    id: "R12",
    theme: "Unify",
    text: "Reuse a consistent template and firm branding.",
    imp: 8.0,
    sat: 5.8,
    basis: "inferred",
    origin:
      "New management estimate. Public references describe template capabilities; assumed higher satisfaction still needs customer validation.",
    sources: ["addepar", "advyzon"],
    ux: "Start from a shared template with controlled branding and reusable sections.",
    tab: "build",
  },
  {
    id: "R13",
    theme: "Explain",
    text: "Let the client explore a report in context.",
    imp: 8.8,
    sat: 2.6,
    basis: "derived",
    origin: "Legacy ODI #8.2; original 8.8 / 2.6 ratings retained.",
    sources: ["portal"],
    ux: "Connect report content to an interactive client view with understandable context.",
    tab: "customize",
  },
  {
    id: "R14",
    theme: "Route",
    text: "Know whether the client received and opened the report.",
    imp: 8.1,
    sat: 3.2,
    basis: "derived",
    origin: "Legacy ODI #8.4; original 8.1 / 3.2 ratings retained.",
    sources: ["portal"],
    ux: "Separate delivery success from actual opening and offer a follow-up action.",
    tab: "generate",
  },
  {
    id: "R15",
    theme: "Unify",
    text: "Preview the chosen sections and date range before generating.",
    imp: 7.8,
    sat: 5.5,
    basis: "inferred",
    origin:
      "New management estimate from the report configuration workflow. Assumed higher satisfaction is not measured.",
    sources: ["advyzon"],
    ux: "Make the report scope and included sections inspectable before generation.",
    tab: "customize",
  },
].map((outcome) => ({
  ...outcome,
  scoreType: "Management estimate",
  coverage:
    outcome.tab === "build"
      ? "Synthetic client and template selection is implemented. Live reconciliation, shared template governance and source integration remain proposed."
      : outcome.tab === "customize"
        ? "Synthetic section, date and presentation controls are implemented. Claim attribution, policy enforcement and interactive client delivery remain proposed."
        : "A synthetic generation pipeline shows stage progress. Live recovery, ownership, approval, retention and delivery tracking remain proposed.",
}));

// Representative outcomes preserve the five recommendation-theme entry points.
export const reportingThemeOutcomeIds = {
  Unify: "R3",
  Explain: "R5",
  Unblock: "R4",
  Route: "R8",
  Prove: "R10",
};
